#include <algorithm>
#include <cstdint>
#include <cstring>
#include <cstdlib>
#include <iterator>
#include <atomic>
#include <new>
#include <string>
#include <utility>
#include <vector>
#include "cJSON.h"
#include "driver/gpio.h"
#include "driver/ledc.h"
#include "driver/uart.h"
#include "driver/adc.h"
#include "esp_timer.h"
#include "esp_system.h"
#include "esp_partition.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/semphr.h"
#include "mbedtls/base64.h"
#include "nvs.h"
#include "nvs_flash.h"

#ifndef CAPI_BOARD_ID
#define CAPI_BOARD_ID "wemos-d1-r32"
#endif
#define CAPI_FIRMWARE_VERSION "1.0.0"
static constexpr uint16_t ABI = 1;
static constexpr size_t MAX_RULES = 32 * 1024;
static constexpr uart_port_t LINK = UART_NUM_0;

static std::vector<uint8_t> candidate;
static size_t expected_bytes = 0;
static uint32_t expected_crc = 0;
static cJSON *active = nullptr;
static volatile bool running = false, paused = false;
static std::atomic<int> active_tasks{0};
static std::atomic<int> task_states[32]; // 0 inactive, 1 running, 2 done
static std::atomic<int32_t> counter_value{0};
struct RuntimeValue { enum Kind { NUMBER, TEXT, BOOLEAN } kind=NUMBER; int32_t number=0; bool boolean=false; std::string text; };
struct RuntimeVariable { std::string id; RuntimeValue value; };
static std::vector<RuntimeVariable> variables;
static SemaphoreHandle_t variables_mutex = nullptr;
static int pwm_pins[8] = {-1,-1,-1,-1,-1,-1,-1,-1};
static int pwm_timers[8] = {-1,-1,-1,-1,-1,-1,-1,-1};
static int output_pins[32] = {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1};
static portMUX_TYPE gpio_mux=portMUX_INITIALIZER_UNLOCKED;
static bool timer_ready[3] = {false,false,false};
static std::atomic<uint32_t> buzzer_epochs[GPIO_NUM_MAX];
struct MatrixState { int din=-1,clk=-1,cs=-1;bool reverse=true,rotated=false;uint32_t rows[8]={};std::string text;int offset=0,repeats=0,speed=100;TickType_t next=0;bool active=false,ready=false; };
static MatrixState matrix;
static SemaphoreHandle_t matrix_mutex=nullptr;
static constexpr uart_port_t MESSAGE_UART = UART_NUM_1;
static bool message_uart_ready=false;
static SemaphoreHandle_t message_mutex=nullptr;
static std::string message_last;
struct MessageParser { uint8_t state=0;uint16_t length=0,position=0,crc=0xffff,received_crc=0;char value[121]={}; };
static MessageParser message_parser;
struct OttoState { cJSON *device=nullptr;std::atomic<int> owner{-1};std::atomic<int> distance{0};uint8_t sonar_state=0,sound_preset=0,sound_step=5;uint64_t sonar_at=0,echo_started=0;TickType_t sound_at=0;bool ready=false; };
static OttoState otto;
static SemaphoreHandle_t otto_mutex=nullptr;

static uint32_t crc32(const uint8_t *data, size_t size) {
  uint32_t value = 0xffffffff;
  for (size_t i = 0; i < size; ++i) { value ^= data[i]; for (int bit = 0; bit < 8; ++bit) value = (value >> 1) ^ (0xedb88320u & -(int32_t)(value & 1)); }
  return value ^ 0xffffffff;
}
static uint16_t u16(const uint8_t *p) { return p[0] | ((uint16_t)p[1] << 8); }
static uint32_t u32(const uint8_t *p) { return p[0] | ((uint32_t)p[1] << 8) | ((uint32_t)p[2] << 16) | ((uint32_t)p[3] << 24); }
static void send_json(cJSON *value) { char *line = cJSON_PrintUnformatted(value); if (line) { uart_write_bytes(LINK, line, strlen(line)); uart_write_bytes(LINK, "\n", 1); free(line); } cJSON_Delete(value); }
static void reply(const char *type, const char *message = nullptr) { cJSON *out = cJSON_CreateObject(); cJSON_AddStringToObject(out, "type", type); if (message) cJSON_AddStringToObject(out, "message", message); send_json(out); }
static void telemetry(const char *event, const char *block, const char *message) { cJSON *out = cJSON_CreateObject(); cJSON_AddStringToObject(out, "type", "TELEMETRY"); cJSON_AddStringToObject(out, "event", event); if (block) cJSON_AddStringToObject(out, "blockId", block); if (message) cJSON_AddStringToObject(out, "message", message); send_json(out); }
static void telemetry_state(const char *event,const char *block,const char *device_id,const std::string &value){cJSON *out=cJSON_CreateObject();cJSON_AddStringToObject(out,"type","TELEMETRY");cJSON_AddStringToObject(out,"event",event);if(block)cJSON_AddStringToObject(out,"blockId",block);if(device_id&&device_id[0])cJSON_AddStringToObject(out,"deviceId",device_id);cJSON_AddStringToObject(out,"value",value.c_str());send_json(out);}
static const char *text(cJSON *object, const char *key, const char *fallback = "") { cJSON *item = cJSON_GetObjectItemCaseSensitive(object, key); return cJSON_IsString(item) && item->valuestring ? item->valuestring : fallback; }
static int number(cJSON *object, const char *key, int fallback = 0) { cJSON *item = cJSON_GetObjectItemCaseSensitive(object, key); return cJSON_IsNumber(item) ? item->valueint : fallback; }
static cJSON *device(const char *id) {
  cJSON *resources = cJSON_GetObjectItem(active, "resources"), *devices = resources ? cJSON_GetObjectItem(resources, "devices") : nullptr, *item;
  cJSON_ArrayForEach(item, devices) if (!strcmp(text(item, "id"), id)) return item;
  return nullptr;
}
static int pin(cJSON *dev, const char *key) { cJSON *pins = dev ? cJSON_GetObjectItem(dev, "pins") : nullptr; cJSON *item = pins ? cJSON_GetObjectItem(pins, key) : nullptr; return cJSON_IsNumber(item) ? item->valueint : -1; }
static int analog_read(int gpio) {
  int channel=-1;
  if(!strcmp(CAPI_BOARD_ID,"wemos-d1-r32")){switch(gpio){case 36:channel=ADC1_CHANNEL_0;break;case 39:channel=ADC1_CHANNEL_3;break;case 34:channel=ADC1_CHANNEL_6;break;case 35:channel=ADC1_CHANNEL_7;break;default:return 0;}}
  else if(gpio>=1&&gpio<=10)channel=gpio-1;else return 0;
  adc1_config_width(ADC_WIDTH_BIT_12);adc1_config_channel_atten((adc1_channel_t)channel,ADC_ATTEN_DB_11);return adc1_get_raw((adc1_channel_t)channel);
}
static void matrix_flush();
static void output(int gpio,int level){if(gpio<0||gpio>=GPIO_NUM_MAX)return;bool configured=false;portENTER_CRITICAL(&gpio_mux);for(int i=0;i<32;++i){if(output_pins[i]==gpio){configured=true;break;}if(output_pins[i]<0){output_pins[i]=gpio;break;}}portEXIT_CRITICAL(&gpio_mux);if(!configured){gpio_reset_pin((gpio_num_t)gpio);gpio_set_direction((gpio_num_t)gpio,GPIO_MODE_OUTPUT);}gpio_set_level((gpio_num_t)gpio,level);}
static void safe_outputs() { otto.owner=-1;for(int i=0;i<8;++i)if(pwm_pins[i]>=0){ledc_set_duty(LEDC_LOW_SPEED_MODE,(ledc_channel_t)i,0);ledc_update_duty(LEDC_LOW_SPEED_MODE,(ledc_channel_t)i);} for(int gpio:output_pins)if(gpio>=0)gpio_set_level((gpio_num_t)gpio,0);if(matrix_mutex)xSemaphoreTake(matrix_mutex,portMAX_DELAY);matrix.active=false;memset(matrix.rows,0,sizeof(matrix.rows));matrix_flush();if(matrix_mutex)xSemaphoreGive(matrix_mutex); }
static int ledc_channel(int gpio,int timer,int frequency,ledc_timer_bit_t resolution){if(gpio<0||gpio>=GPIO_NUM_MAX||timer<0||timer>2)return -1;if(!timer_ready[timer]){ledc_timer_config_t config={};config.speed_mode=LEDC_LOW_SPEED_MODE;config.duty_resolution=resolution;config.timer_num=(ledc_timer_t)timer;config.freq_hz=frequency;config.clk_cfg=LEDC_AUTO_CLK;if(ledc_timer_config(&config)!=ESP_OK)return -1;timer_ready[timer]=true;}else if(timer==2)ledc_set_freq(LEDC_LOW_SPEED_MODE,(ledc_timer_t)timer,frequency);int channel=-1;for(int i=0;i<8;++i)if(pwm_pins[i]==gpio){return pwm_timers[i]==timer?i:-1;}else if(channel<0&&pwm_pins[i]<0)channel=i;if(channel<0)return -1;ledc_channel_config_t config={};config.gpio_num=gpio;config.speed_mode=LEDC_LOW_SPEED_MODE;config.channel=(ledc_channel_t)channel;config.intr_type=LEDC_INTR_DISABLE;config.timer_sel=(ledc_timer_t)timer;config.duty=0;config.hpoint=0;if(ledc_channel_config(&config)!=ESP_OK)return -1;pwm_pins[channel]=gpio;pwm_timers[channel]=timer;return channel;}
static bool write_ledc(int gpio,int timer,int frequency,ledc_timer_bit_t resolution,uint32_t duty){int channel=ledc_channel(gpio,timer,frequency,resolution);return channel>=0&&ledc_set_duty(LEDC_LOW_SPEED_MODE,(ledc_channel_t)channel,duty)==ESP_OK&&ledc_update_duty(LEDC_LOW_SPEED_MODE,(ledc_channel_t)channel)==ESP_OK;}
static bool pwm(int gpio,int percent){return write_ledc(gpio,0,5000,LEDC_TIMER_8_BIT,(uint32_t)std::clamp(percent,0,100)*255/100);}
static bool servo(int gpio,int angle){uint32_t pulse=500U+(uint32_t)std::clamp(angle,0,180)*2000U/180U;return write_ledc(gpio,1,50,LEDC_TIMER_14_BIT,pulse*16383U/20000U);}
struct BuzzerStop { int gpio; bool active; uint32_t epoch; uint32_t duration; };
static void stop_buzzer_task(void *parameter){BuzzerStop *stop=(BuzzerStop*)parameter;vTaskDelay(pdMS_TO_TICKS(stop->duration));if(buzzer_epochs[stop->gpio]==stop->epoch){if(stop->active)output(stop->gpio,0);else{int channel=ledc_channel(stop->gpio,2,1000,LEDC_TIMER_8_BIT);if(channel>=0){ledc_set_duty(LEDC_LOW_SPEED_MODE,(ledc_channel_t)channel,0);ledc_update_duty(LEDC_LOW_SPEED_MODE,(ledc_channel_t)channel);}}}delete stop;vTaskDelete(nullptr);}
static void buzzer(cJSON *dev,bool active,int frequency,int duration){int gpio=pin(dev,"signal");if(gpio<0||gpio>=GPIO_NUM_MAX)return;uint32_t epoch=++buzzer_epochs[gpio];if(active)output(gpio,1);else write_ledc(gpio,2,std::clamp(frequency,20,20000),LEDC_TIMER_8_BIT,128);BuzzerStop *stop=new(std::nothrow) BuzzerStop{gpio,active,epoch,(uint32_t)std::clamp(duration,0,60000)};if(!stop||xTaskCreate(stop_buzzer_task,"capi-tone",2048,stop,4,nullptr)!=pdPASS){delete stop;if(active)output(gpio,0);}}
static uint16_t message_crc_byte(uint16_t crc,uint8_t value){crc^=(uint16_t)value<<8;for(uint8_t bit=0;bit<8;++bit)crc=(crc&0x8000)?(uint16_t)((crc<<1)^0x1021):(uint16_t)(crc<<1);return crc;}
static void message_reset(){message_parser=MessageParser{};}
static int message_consume(uint8_t byte,char *result){switch(message_parser.state){case 0:if(byte==0x43)message_parser.state=1;return 0;case 1:if(byte==0x42)message_parser.state=2;else message_parser.state=byte==0x43?1:0;return 0;case 2:if(byte!=1){message_reset();return -1;}message_parser.crc=message_crc_byte(0xffff,byte);message_parser.state=3;return 0;case 3:message_parser.length=byte;message_parser.crc=message_crc_byte(message_parser.crc,byte);message_parser.state=4;return 0;case 4:message_parser.length|=(uint16_t)byte<<8;message_parser.crc=message_crc_byte(message_parser.crc,byte);if(!message_parser.length||message_parser.length>120){message_reset();return -1;}message_parser.position=0;message_parser.state=5;return 0;case 5:message_parser.value[message_parser.position++]=(char)byte;message_parser.crc=message_crc_byte(message_parser.crc,byte);if(message_parser.position==message_parser.length){message_parser.value[message_parser.position]=0;message_parser.state=6;}return 0;case 6:message_parser.received_crc=byte;message_parser.state=7;return 0;case 7:message_parser.received_crc|=(uint16_t)byte<<8;message_parser.state=8;return 0;case 8:if(byte!=0x0d){message_reset();return -1;}message_parser.state=9;return 0;case 9:{bool valid=byte==0x0a&&message_parser.received_crc==message_parser.crc;if(valid)memcpy(result,message_parser.value,message_parser.length+1);message_reset();return valid?1:-1;}}message_reset();return -1;}
static int message_poll(char *result){if(!message_uart_ready)return 0;uint8_t byte=0;for(int budget=0;budget<64;++budget){if(uart_read_bytes(MESSAGE_UART,&byte,1,0)!=1)break;int parsed=message_consume(byte,result);if(parsed)return parsed;}return 0;}
static bool message_send(const std::string &value){if(!message_uart_ready||value.empty()||value.size()>120)return false;uint8_t packet[129]={0x43,0x42,1,(uint8_t)(value.size()&0xff),(uint8_t)(value.size()>>8)};memcpy(packet+5,value.data(),value.size());uint16_t crc=0xffff;for(size_t index=2;index<5+value.size();++index)crc=message_crc_byte(crc,packet[index]);packet[5+value.size()]=crc&0xff;packet[6+value.size()]=crc>>8;packet[7+value.size()]=0x0d;packet[8+value.size()]=0x0a;size_t total=value.size()+9;return uart_write_bytes(MESSAGE_UART,packet,total)==(int)total;}
static bool message_begin(){if(message_uart_ready){uart_driver_delete(MESSAGE_UART);message_uart_ready=false;}message_reset();cJSON *resources=active?cJSON_GetObjectItem(active,"resources"):nullptr,*devices=resources?cJSON_GetObjectItem(resources,"devices"):nullptr,*dev;cJSON_ArrayForEach(dev,devices)if(!strcmp(text(dev,"kind"),"messages")){cJSON *config=cJSON_GetObjectItem(dev,"config");uart_config_t uart={};uart.baud_rate=number(config,"baudRate",9600);uart.data_bits=UART_DATA_8_BITS;uart.parity=UART_PARITY_DISABLE;uart.stop_bits=UART_STOP_BITS_1;uart.flow_ctrl=UART_HW_FLOWCTRL_DISABLE;uart.source_clk=UART_SCLK_DEFAULT;int tx=pin(dev,"tx"),rx=pin(dev,"rx");if(uart_param_config(MESSAGE_UART,&uart)!=ESP_OK||uart_set_pin(MESSAGE_UART,tx<0?UART_PIN_NO_CHANGE:tx,rx<0?UART_PIN_NO_CHANGE:rx,UART_PIN_NO_CHANGE,UART_PIN_NO_CHANGE)!=ESP_OK||uart_driver_install(MESSAGE_UART,512,512,0,nullptr,0)!=ESP_OK)return false;message_uart_ready=true;return true;}return true;}
static int otto_center(int index){cJSON *config=otto.device?cJSON_GetObjectItem(otto.device,"config"):nullptr,*centers=config?cJSON_GetObjectItem(config,"centers"):nullptr,*value=centers?cJSON_GetArrayItem(centers,index):nullptr;return cJSON_IsNumber(value)?std::clamp(value->valueint,0,180):90;}
static bool otto_reversed(int index){cJSON *config=otto.device?cJSON_GetObjectItem(otto.device,"config"):nullptr,*items=config?cJSON_GetObjectItem(config,"reversed"):nullptr;return cJSON_IsTrue(items?cJSON_GetArrayItem(items,index):nullptr);}
static int otto_pin(int index){static const char *keys[]={"leftLeg","rightLeg","leftFoot","rightFoot","leftArm","rightArm"};return pin(otto.device,keys[index]);}
static void otto_pose(int a,int b,int c,int d){int values[]={a,b,c,d};for(int i=0;i<4;++i){int gpio=otto_pin(i);if(gpio>=0)servo(gpio,std::clamp(otto_center(i)+(otto_reversed(i)?-values[i]:values[i]),0,180));}}
static void otto_home(){otto_pose(0,0,0,0);}
static void otto_move(int action,int phase){static const int8_t poses[17][4][4]={{{-18,18,12,12},{18,-18,12,12},{18,-18,-12,-12},{-18,18,-12,-12}},{{18,-18,12,12},{-18,18,12,12},{-18,18,-12,-12},{18,-18,-12,-12}},{{-22,-8,14,-14},{8,22,14,-14},{8,22,-14,14},{-22,-8,-14,14}},{{8,22,14,-14},{-22,-8,14,-14},{-22,-8,-14,14},{8,22,-14,14}},{{-25,25,-18,18},{25,-25,18,-18},{-25,25,18,-18},{25,-25,-18,18}},{{0,0,28,-28},{0,0,-28,28},{0,0,28,-28},{0,0,0,0}},{{-20,-20,0,0},{20,20,0,0},{-20,-20,0,0},{20,20,0,0}},{{0,0,18,18},{0,0,-18,-18},{0,0,18,18},{0,0,-18,-18}},{{-8,8,-8,8},{8,-8,8,-8},{-8,8,-8,8},{8,-8,8,-8}},{{-18,-6,22,-8},{8,18,-8,22},{18,6,-22,8},{-8,-18,8,-22}},{{6,18,-8,22},{-18,-6,22,-8},{-6,-18,8,-22},{18,6,-22,8}},{{-28,0,18,0},{-28,0,-18,0},{0,0,0,0},{0,0,0,0}},{{0,28,0,-18},{0,28,0,18},{0,0,0,0},{0,0,0,0}},{{-25,0,25,0},{8,0,-8,0},{-25,0,25,0},{0,0,0,0}},{{0,25,0,-25},{0,-8,0,8},{0,25,0,-25},{0,0,0,0}},{{-18,18,25,25},{18,-18,-25,-25},{-18,18,25,25},{18,-18,-25,-25}},{{18,-18,25,25},{-18,18,-25,-25},{18,-18,25,25},{-18,18,-25,-25}}};const int8_t *pose=poses[std::clamp(action,0,16)][phase%4];otto_pose(pose[0],pose[1],pose[2],pose[3]);}
static void otto_arms(int pose){static const int8_t values[5][2]={{0,0},{-65,65},{-65,0},{0,65},{-45,45}};pose=std::clamp(pose,0,4);for(int i=0;i<2;++i){int gpio=otto_pin(i+4);if(gpio>=0)servo(gpio,std::clamp(otto_center(i+4)+(otto_reversed(i+4)?-values[pose][i]:values[pose][i]),0,180));}}
static void otto_matrix_send(uint8_t address,uint8_t value){int din=pin(otto.device,"matrixDin"),clk=pin(otto.device,"matrixClk"),cs=pin(otto.device,"matrixCs");if(din<0||clk<0||cs<0)return;output(cs,0);uint16_t packet=((uint16_t)address<<8)|value;for(int bit=15;bit>=0;--bit){output(clk,0);output(din,(packet>>bit)&1);output(clk,1);}output(cs,1);}
static void otto_expression(int expression){static const uint8_t faces[7][8]={{0x00,0x42,0x00,0x00,0x42,0x24,0x18,0x00},{0x00,0x42,0x00,0x00,0x18,0x24,0x42,0x00},{0x00,0x66,0x00,0x00,0x3c,0x42,0x00,0x00},{0x00,0x42,0x00,0x18,0x24,0x24,0x18,0x00},{0x00,0x00,0x66,0x00,0x00,0x3c,0x00,0x00},{0x00,0x66,0xff,0xff,0x7e,0x3c,0x18,0x00},{0,0,0,0,0,0,0,0}};expression=std::clamp(expression,0,6);for(int row=0;row<8;++row)otto_matrix_send(row+1,faces[expression][row]);}
static void otto_sound(int preset){otto.sound_preset=std::clamp(preset,0,7);otto.sound_step=0;otto.sound_at=xTaskGetTickCount();}
static void otto_service(void*){for(;;){if(otto_mutex)xSemaphoreTake(otto_mutex,portMAX_DELAY);if(otto.ready){TickType_t now=xTaskGetTickCount();int buzzer_pin=pin(otto.device,"buzzer");if(buzzer_pin>=0&&otto.sound_step<5&&now>=otto.sound_at){static const uint16_t notes[8][4]={{523,659,784,1047},{392,330,262,196},{784,1047,1319,0},{659,523,659,392},{262,220,196,0},{880,0,0,0},{523,659,784,0},{110,98,82,0}};int frequency=otto.sound_step<4?notes[otto.sound_preset][otto.sound_step]:0;write_ledc(buzzer_pin,2,std::max(frequency,20),LEDC_TIMER_8_BIT,frequency?128:0);++otto.sound_step;otto.sound_at=now+pdMS_TO_TICKS(140);}int trigger=pin(otto.device,"trigger"),echo=pin(otto.device,"echo");if(trigger>=0&&echo>=0){uint64_t us=esp_timer_get_time();int level=gpio_get_level((gpio_num_t)echo);switch(otto.sonar_state){case 0:if(us-otto.sonar_at>=60000){output(trigger,0);otto.sonar_at=us;otto.sonar_state=1;}break;case 1:if(us-otto.sonar_at>=2){output(trigger,1);otto.sonar_at=us;otto.sonar_state=2;}break;case 2:if(us-otto.sonar_at>=10){output(trigger,0);otto.sonar_at=us;otto.sonar_state=3;}break;case 3:if(level){otto.echo_started=us;otto.sonar_state=4;}else if(us-otto.sonar_at>30000){otto.distance=0;otto.sonar_at=us;otto.sonar_state=0;}break;case 4:if(!level){otto.distance=std::min<int>((us-otto.echo_started)/58,500);otto.sonar_at=us;otto.sonar_state=0;}else if(us-otto.echo_started>30000){otto.distance=0;otto.sonar_at=us;otto.sonar_state=0;}break;}}}if(otto_mutex)xSemaphoreGive(otto_mutex);vTaskDelay(pdMS_TO_TICKS(1));}}
static void otto_begin(){otto.ready=false;otto.device=nullptr;otto.owner=-1;otto.distance=0;otto.sonar_state=0;otto.sound_step=5;cJSON *resources=active?cJSON_GetObjectItem(active,"resources"):nullptr,*devices=resources?cJSON_GetObjectItem(resources,"devices"):nullptr,*dev;cJSON_ArrayForEach(dev,devices)if(!strcmp(text(dev,"kind"),"otto")){otto.device=dev;int echo=pin(dev,"echo");if(echo>=0){gpio_set_direction((gpio_num_t)echo,GPIO_MODE_INPUT);otto.sonar_at=esp_timer_get_time();}otto.ready=true;otto_home();otto_arms(0);if(pin(dev,"matrixCs")>=0){otto_matrix_send(0x0f,0);otto_matrix_send(0x0c,1);otto_matrix_send(0x0b,7);otto_matrix_send(0x09,0);cJSON *config=cJSON_GetObjectItem(dev,"config");otto_matrix_send(0x0a,std::clamp(number(config,"matrixBrightness",4),0,15));otto_expression(0);}break;}}
static void matrix_shift(uint8_t address,uint8_t data){uint16_t packet=((uint16_t)address<<8)|data;for(int bit=15;bit>=0;--bit){output(matrix.clk,0);output(matrix.din,(packet>>bit)&1);output(matrix.clk,1);}}
static uint8_t reverse_byte(uint8_t value){value=(value&0xf0)>>4|(value&0x0f)<<4;value=(value&0xcc)>>2|(value&0x33)<<2;return (value&0xaa)>>1|(value&0x55)<<1;}
static void matrix_register(uint8_t address,uint8_t data){output(matrix.cs,0);for(int module=0;module<4;++module)matrix_shift(address,data);output(matrix.cs,1);}
static void matrix_flush(){if(!matrix.ready)return;for(int physical_row=0;physical_row<8;++physical_row){output(matrix.cs,0);for(int physical_module=3;physical_module>=0;--physical_module){int logical=matrix.reverse?3-physical_module:physical_module;if(matrix.rotated)logical=3-logical;int row=matrix.rotated?7-physical_row:physical_row;uint8_t data=(matrix.rows[row]>>((3-logical)*8))&0xff;if(matrix.rotated)data=reverse_byte(data);matrix_shift(physical_row+1,data);}output(matrix.cs,1);}}
static uint8_t matrix_glyph(char character,int column){static const char symbols[]="ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789? ";static const uint8_t glyphs[][5]={{126,17,17,17,126},{127,73,73,73,54},{62,65,65,65,34},{127,65,65,34,28},{127,73,73,73,65},{127,9,9,9,1},{62,65,73,73,122},{127,8,8,8,127},{65,65,127,65,65},{32,64,65,63,1},{127,8,20,34,65},{127,64,64,64,64},{127,2,12,2,127},{127,4,8,16,127},{62,65,65,65,62},{127,9,9,9,6},{62,65,81,33,94},{127,9,25,41,70},{38,73,73,73,50},{1,1,127,1,1},{63,64,64,64,63},{31,32,64,32,31},{127,32,24,32,127},{99,20,8,20,99},{3,4,120,4,3},{97,81,73,69,67},{62,69,73,81,62},{0,66,127,64,0},{98,81,73,73,70},{34,65,73,73,54},{24,20,18,127,16},{47,73,73,73,49},{62,73,73,73,50},{1,1,113,9,7},{54,73,73,73,54},{38,73,73,73,62},{2,1,81,9,6},{0,0,0,0,0}};if(column<0||column>=5)return 0;const char *found=strchr(symbols,character);int index=found?found-symbols:36;return glyphs[index][column];}
static void matrix_service(void*){for(;;){if(matrix_mutex)xSemaphoreTake(matrix_mutex,portMAX_DELAY);TickType_t now=xTaskGetTickCount();if(matrix.active&&now>=matrix.next){memset(matrix.rows,0,sizeof(matrix.rows));int width=matrix.text.size()*6;for(int x=0;x<32;++x){int source=matrix.offset+x-32;uint8_t column=source>=0&&source<width?matrix_glyph(matrix.text[source/6],source%6):0;for(int y=0;y<7;++y)if(column&(1<<y))matrix.rows[y]|=1UL<<(31-x);}matrix_flush();++matrix.offset;matrix.next=now+pdMS_TO_TICKS(matrix.speed);if(matrix.offset>width+32){if(matrix.repeats==1)matrix.active=false;else{if(matrix.repeats>1)--matrix.repeats;matrix.offset=0;}}}if(matrix_mutex)xSemaphoreGive(matrix_mutex);vTaskDelay(pdMS_TO_TICKS(5));}}
static void matrix_begin(){matrix.ready=false;cJSON *resources=active?cJSON_GetObjectItem(active,"resources"):nullptr,*devices=resources?cJSON_GetObjectItem(resources,"devices"):nullptr,*dev;cJSON_ArrayForEach(dev,devices)if(!strcmp(text(dev,"kind"),"ledMatrix")){matrix.din=pin(dev,"din");matrix.clk=pin(dev,"clk");matrix.cs=pin(dev,"cs");cJSON *config=cJSON_GetObjectItem(dev,"config");matrix.reverse=!strcmp(text(config,"order","right-to-left"),"right-to-left");matrix.rotated=!strcmp(text(config,"orientation"),"rotated");matrix.ready=true;output(matrix.cs,1);output(matrix.clk,0);matrix_register(0x0f,0);matrix_register(0x0c,1);matrix_register(0x0b,7);matrix_register(0x09,0);matrix_register(0x0a,std::clamp(number(config,"brightness",5),0,15));memset(matrix.rows,0,sizeof(matrix.rows));matrix_flush();break;}}
static void motor(cJSON *dev, int power, bool robot_side = false, bool right = false) {
  const char *a = robot_side ? (right ? "rightIn1" : "leftIn1") : "in1";
  const char *b = robot_side ? (right ? "rightIn2" : "leftIn2") : "in2";
  pwm(pin(dev, a), power > 0 ? std::abs(power) : 0); pwm(pin(dev, b), power < 0 ? std::abs(power) : 0);
}
static bool allowed_pin(int value) {
  if (value < 0) return true;
  static const int wemos[] = {4,13,14,16,17,18,19,23,25,26,27,34,35,36,39};
  static const int s3[] = {1,2,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,21,38,39,40,41,42,47};
  const int *values = !strcmp(CAPI_BOARD_ID,"wemos-d1-r32") ? wemos : s3;
  size_t count = !strcmp(CAPI_BOARD_ID,"wemos-d1-r32") ? sizeof(wemos)/sizeof(*wemos) : sizeof(s3)/sizeof(*s3);
  return std::find(values, values + count, value) != values + count;
}
static bool allowed_output_pin(int value){if(value<0)return false;static const int wemos[]={13,14,16,17,18,19,23,25,26,27};static const int s3[]={4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,21,38,39,40,41,42,47};const int *values=!strcmp(CAPI_BOARD_ID,"wemos-d1-r32")?wemos:s3;size_t count=!strcmp(CAPI_BOARD_ID,"wemos-d1-r32")?sizeof(wemos)/sizeof(*wemos):sizeof(s3)/sizeof(*s3);return std::find(values,values+count,value)!=values+count;}
static bool supported_operation(const char *op) {
  static const char *values[] = {"halt","wait","counterSet","counterChange","variableSet","variableChange","pin","led","traffic","motor","robot","otto","ottoSound","ottoExpression","ottoArms","servo","buzzer","tone","serial","messageSend","messageReceiveWait","matrixClear","matrixPixel","matrixPattern","matrixScroll","visualWait","repeatStart","repeatNext","jump","jumpIfFalse","fork","join"};
  return std::find_if(std::begin(values),std::end(values),[op](const char *value){return !strcmp(op,value);}) != std::end(values);
}
static bool supported_expression(cJSON *expression){if(!cJSON_IsObject(expression))return false;const char *kind=text(expression,"kind");if(!strcmp(kind,"number")||!strcmp(kind,"text")||!strcmp(kind,"boolean")||!strcmp(kind,"counterValue")||!strcmp(kind,"sensorValue")||!strcmp(kind,"buttonValue")||!strcmp(kind,"barrierValue")||!strcmp(kind,"messageValue")||!strcmp(kind,"ottoDistance")||!strcmp(kind,"variable"))return true;if(!strcmp(kind,"join")){cJSON *parts=cJSON_GetObjectItem(expression,"parts"),*part;if(!cJSON_IsArray(parts))return false;cJSON_ArrayForEach(part,parts)if(!supported_expression(part))return false;return true;}if(!strcmp(kind,"math"))return supported_expression(cJSON_GetObjectItem(expression,"left"))&&supported_expression(cJSON_GetObjectItem(expression,"right"));return false;}
static bool supported_condition(cJSON *condition){if(!cJSON_IsObject(condition))return false;const char *kind=text(condition,"kind");if(!strcmp(kind,"boolean")||!strcmp(kind,"counter")||!strcmp(kind,"compare")||!strcmp(kind,"sensor")||!strcmp(kind,"buttonPressed"))return true;if(!strcmp(kind,"value"))return supported_expression(cJSON_GetObjectItem(condition,"expression"));if(!strcmp(kind,"valueCompare"))return supported_expression(cJSON_GetObjectItem(condition,"left"))&&supported_expression(cJSON_GetObjectItem(condition,"right"));return false;}
static bool contains_device(cJSON *devices,const char *id){cJSON *item;cJSON_ArrayForEach(item,devices)if(!strcmp(text(item,"id"),id))return true;return false;}
static bool operation_device_valid(cJSON *devices,const char *op,const char *id){if(!id[0])return true;cJSON *item;cJSON_ArrayForEach(item,devices)if(!strcmp(text(item,"id"),id)){const char *kind=text(item,"kind");return !strcmp(op,"led")?!strcmp(kind,"led"):!strcmp(op,"traffic")?!strcmp(kind,"trafficLight"):!strcmp(op,"motor")?!strcmp(kind,"motor"):!strcmp(op,"robot")?!strcmp(kind,"robot"):!strncmp(op,"otto",4)?!strcmp(kind,"otto"):!strcmp(op,"servo")?!strcmp(kind,"servo"):!strcmp(op,"buzzer")?(!strcmp(kind,"activeBuzzer")||!strcmp(kind,"passiveBuzzer")):!strcmp(op,"tone")?!strcmp(kind,"passiveBuzzer"):!strncmp(op,"message",7)?!strcmp(kind,"messages"):!strncmp(op,"matrix",6)?!strcmp(kind,"ledMatrix"):!strcmp(op,"visualWait")?!strcmp(kind,"ledMatrix"):true;}return false;}
static bool validate_rules(const std::vector<uint8_t> &bytes, cJSON **document) {
  if (bytes.size() < 32 || bytes.size() > MAX_RULES || memcmp(bytes.data(), "CAPIRULE", 8) || u16(&bytes[8]) != 1 || u16(&bytes[10]) != ABI || u32(&bytes[12]) != bytes.size() - 32 || u32(&bytes[16]) != crc32(&bytes[32], bytes.size() - 32)) return false;
  std::string payload((const char *)&bytes[32], bytes.size() - 32); cJSON *root = cJSON_ParseWithLength(payload.data(), payload.size());
  cJSON *tasks=root?cJSON_GetObjectItem(root,"tasks"):nullptr,*resources=root?cJSON_GetObjectItem(root,"resources"):nullptr,*devices=resources?cJSON_GetObjectItem(resources,"devices"):nullptr;
  if (!root || strcmp(text(root, "format"), "CapiRules") || strcmp(text(root, "board"), CAPI_BOARD_ID) || number(root, "abi") != ABI || !cJSON_IsArray(tasks) || cJSON_GetArraySize(tasks)>32 || !cJSON_IsArray(devices) || cJSON_GetArraySize(devices)>64 || u32(&bytes[20])>2048 || u32(&bytes[24])!=(uint32_t)cJSON_GetArraySize(devices) || u32(&bytes[28])!=(uint32_t)cJSON_GetArraySize(tasks)) { cJSON_Delete(root); return false; }
  cJSON *item,*pins,*pin_item,*task,*instruction;int message_devices=0,otto_devices=0;cJSON_ArrayForEach(item,devices){pins=cJSON_GetObjectItem(item,"pins"); if(!cJSON_IsObject(pins)){cJSON_Delete(root);return false;} cJSON_ArrayForEach(pin_item,pins) if(cJSON_IsNumber(pin_item)&&!allowed_pin(pin_item->valueint)){cJSON_Delete(root);return false;}const char *kind=text(item,"kind");if(!strcmp(kind,"led")||!strcmp(kind,"trafficLight")||!strcmp(kind,"motor")||!strcmp(kind,"robot")||!strcmp(kind,"servo")||!strcmp(kind,"activeBuzzer")||!strcmp(kind,"passiveBuzzer")||!strcmp(kind,"ledMatrix"))cJSON_ArrayForEach(pin_item,pins)if(cJSON_IsNumber(pin_item)&&!allowed_output_pin(pin_item->valueint)){cJSON_Delete(root);return false;}if(!strcmp(kind,"otto")){++otto_devices;cJSON *echo=cJSON_GetObjectItem(pins,"echo");cJSON_ArrayForEach(pin_item,pins)if(cJSON_IsNumber(pin_item)&&pin_item!=echo&&!allowed_output_pin(pin_item->valueint)){cJSON_Delete(root);return false;}if(otto_devices>1||(cJSON_IsNumber(echo)&&!allowed_pin(echo->valueint))){cJSON_Delete(root);return false;}}if(!strcmp(kind,"messages")){++message_devices;cJSON *tx=cJSON_GetObjectItem(pins,"tx"),*rx=cJSON_GetObjectItem(pins,"rx"),*config=cJSON_GetObjectItem(item,"config");const char *mode=text(config,"mode");int baud=number(config,"baudRate");if(message_devices>1||(!cJSON_IsNull(tx)&&(!cJSON_IsNumber(tx)||!allowed_output_pin(tx->valueint)))||(!cJSON_IsNull(rx)&&(!cJSON_IsNumber(rx)||!allowed_pin(rx->valueint)))||(strcmp(mode,"send")&&strcmp(mode,"receive")&&strcmp(mode,"both"))||(baud!=9600&&baud!=19200&&baud!=38400&&baud!=57600&&baud!=115200)){cJSON_Delete(root);return false;}}}
  uint32_t instructions=0; cJSON_ArrayForEach(task,tasks){cJSON *output=cJSON_GetObjectItem(task,"output");int output_size=cJSON_GetArraySize(output); if(!cJSON_IsArray(output)){cJSON_Delete(root);return false;} cJSON_ArrayForEach(instruction,output){const char *op=text(instruction,"op"),*device_id=text(instruction,"deviceId");bool target_ok=true;if(!strcmp(op,"jump"))target_ok=number(instruction,"target",-1)>=0&&number(instruction,"target")<output_size;else if(!strcmp(op,"repeatStart"))target_ok=number(instruction,"end",-1)>=0&&number(instruction,"end")<output_size;else if(!strcmp(op,"repeatNext"))target_ok=number(instruction,"target",-1)>=0&&number(instruction,"target")<output_size;else if(!strcmp(op,"jumpIfFalse"))target_ok=number(instruction,"target",-1)>=0&&number(instruction,"target")<output_size;else if(!strcmp(op,"messageReceiveWait"))target_ok=number(instruction,"equalTarget",-1)>=0&&number(instruction,"equalTarget")<output_size&&number(instruction,"differentTarget",-1)>=0&&number(instruction,"differentTarget")<output_size&&number(instruction,"timeoutTarget",-1)>=0&&number(instruction,"timeoutTarget")<=output_size&&number(instruction,"timeoutMs",0)>=100&&number(instruction,"timeoutMs",0)<=300000;else if(!strcmp(op,"pin"))target_ok=allowed_output_pin(number(instruction,"pin",-1));else if(!strcmp(op,"fork")||!strcmp(op,"join")){cJSON *children=cJSON_GetObjectItem(instruction,"children"),*child;target_ok=cJSON_IsArray(children);cJSON_ArrayForEach(child,children)if(!cJSON_IsNumber(child)||child->valueint<0||child->valueint>=cJSON_GetArraySize(tasks))target_ok=false;}if(++instructions>2048||!supported_operation(op)||!target_ok||!operation_device_valid(devices,op,device_id)||(device_id[0]&&!contains_device(devices,device_id))||(!strcmp(op,"jumpIfFalse")&&!supported_condition(cJSON_GetObjectItem(instruction,"condition")))||(!strcmp(op,"variableSet")&&!supported_expression(cJSON_GetObjectItem(instruction,"value")))||(!strcmp(op,"variableChange")&&!supported_expression(cJSON_GetObjectItem(instruction,"delta")))||((!strcmp(op,"serial")||!strcmp(op,"messageSend"))&&cJSON_HasObjectItem(instruction,"expression")&&!supported_expression(cJSON_GetObjectItem(instruction,"expression")))){cJSON_Delete(root);return false;}}}
  if(instructions!=u32(&bytes[20])){cJSON_Delete(root);return false;}
  *document = root; return true;
}

static int32_t value_number(const RuntimeValue &value){if(value.kind==RuntimeValue::NUMBER)return value.number;if(value.kind==RuntimeValue::BOOLEAN)return value.boolean?1:0;char *end=nullptr;long parsed=strtol(value.text.c_str(),&end,10);return end!=value.text.c_str()?(int32_t)std::clamp<long>(parsed,INT32_MIN,INT32_MAX):0;}
static bool value_boolean(const RuntimeValue &value){return value.kind==RuntimeValue::BOOLEAN?value.boolean:value.kind==RuntimeValue::NUMBER?value.number!=0:!value.text.empty();}
static std::string value_text(const RuntimeValue &value){if(value.kind==RuntimeValue::TEXT)return value.text;if(value.kind==RuntimeValue::BOOLEAN)return value.boolean?"sí":"no";return std::to_string(value.number);}
static RuntimeValue evaluate(cJSON *expression){
  RuntimeValue out;const char *kind=text(expression,"kind");
  if(!strcmp(kind,"number")){out.number=number(expression,"value");return out;}
  if(!strcmp(kind,"text")){out.kind=RuntimeValue::TEXT;out.text=text(expression,"value");if(out.text.size()>120)out.text.resize(120);return out;}
  if(!strcmp(kind,"boolean")){out.kind=RuntimeValue::BOOLEAN;out.boolean=cJSON_IsTrue(cJSON_GetObjectItem(expression,"value"));return out;}
  if(!strcmp(kind,"counterValue")){out.number=counter_value;return out;}
  if(!strcmp(kind,"sensorValue")){cJSON *dev=device(text(expression,"deviceId"));out.number=analog_read(pin(dev,"signal"));return out;}
  if(!strcmp(kind,"buttonValue")){cJSON *dev=device(text(expression,"deviceId"));int gpio=pin(dev,"signal");if(gpio>=0){gpio_set_direction((gpio_num_t)gpio,GPIO_MODE_INPUT);out.kind=RuntimeValue::BOOLEAN;out.boolean=gpio_get_level((gpio_num_t)gpio)==0;}return out;}
  if(!strcmp(kind,"barrierValue")){cJSON *dev=device(text(expression,"deviceId"));int gpio=pin(dev,"signal");if(gpio>=0){gpio_set_direction((gpio_num_t)gpio,GPIO_MODE_INPUT);cJSON *config=cJSON_GetObjectItem(dev,"config");bool interrupted=gpio_get_level((gpio_num_t)gpio)==(!strcmp(text(config,"interruptedLevel","LOW"),"HIGH")?1:0);out.kind=RuntimeValue::BOOLEAN;out.boolean=!strcmp(text(expression,"expected"),"CLEAR")?!interrupted:interrupted;}return out;}
  if(!strcmp(kind,"messageValue")){out.kind=RuntimeValue::TEXT;if(message_mutex)xSemaphoreTake(message_mutex,portMAX_DELAY);out.text=message_last;if(message_mutex)xSemaphoreGive(message_mutex);return out;}
  if(!strcmp(kind,"ottoDistance")){out.number=otto.distance.load();return out;}
  if(!strcmp(kind,"variable")){const char *id=text(expression,"variableId");if(variables_mutex)xSemaphoreTake(variables_mutex,portMAX_DELAY);for(const auto &variable:variables)if(variable.id==id){out=variable.value;break;}if(variables_mutex)xSemaphoreGive(variables_mutex);return out;}
  if(!strcmp(kind,"join")){out.kind=RuntimeValue::TEXT;cJSON *parts=cJSON_GetObjectItem(expression,"parts"),*part;cJSON_ArrayForEach(part,parts){out.text+=value_text(evaluate(part));if(out.text.size()>120){out.text.resize(120);break;}}return out;}
  if(!strcmp(kind,"math")){RuntimeValue left=evaluate(cJSON_GetObjectItem(expression,"left")),right=evaluate(cJSON_GetObjectItem(expression,"right"));int32_t a=value_number(left),b=value_number(right);const char *op=text(expression,"operator");int64_t result=!strcmp(op,"ADD")?(int64_t)a+b:!strcmp(op,"SUBTRACT")?(int64_t)a-b:!strcmp(op,"MULTIPLY")?(int64_t)a*b:b?(int64_t)a/b:0;out.number=(int32_t)std::clamp<int64_t>(result,INT32_MIN,INT32_MAX);return out;}
  return out;
}
static void initialize_variables(){variables.clear();cJSON *items=cJSON_GetObjectItem(active,"variables"),*item;cJSON_ArrayForEach(item,items){RuntimeVariable variable;variable.id=text(item,"id");const char *type=text(item,"type");if(!strcmp(type,"text"))variable.value.kind=RuntimeValue::TEXT;else if(!strcmp(type,"boolean"))variable.value.kind=RuntimeValue::BOOLEAN;variables.push_back(std::move(variable));}}
struct StoredRules { char magic[8]; uint32_t size; uint32_t crc; };
static const esp_partition_t *rules_partition(uint8_t slot) { return esp_partition_find_first(ESP_PARTITION_TYPE_DATA, (esp_partition_subtype_t)(slot ? 0x41 : 0x40), slot ? "rules_b" : "rules_a"); }
static uint8_t active_slot() { nvs_handle_t handle; uint8_t slot=0; if(nvs_open("capi",NVS_READONLY,&handle)==ESP_OK){nvs_get_u8(handle,"slot",&slot);nvs_close(handle);} return slot>1?0:slot; }
static bool persist(const std::vector<uint8_t> &bytes) {
  uint8_t slot=1-active_slot(); const esp_partition_t *partition=rules_partition(slot); if(!partition||bytes.size()+sizeof(StoredRules)>partition->size)return false;
  StoredRules header={{'C','A','P','I','S','T','O','R'},(uint32_t)bytes.size(),crc32(bytes.data(),bytes.size())};
  if(esp_partition_erase_range(partition,0,partition->size)!=ESP_OK||esp_partition_write(partition,0,&header,sizeof(header))!=ESP_OK||esp_partition_write(partition,sizeof(header),bytes.data(),bytes.size())!=ESP_OK)return false;
  std::vector<uint8_t> check(bytes.size()); StoredRules read{}; if(esp_partition_read(partition,0,&read,sizeof(read))!=ESP_OK||esp_partition_read(partition,sizeof(read),check.data(),check.size())!=ESP_OK||memcmp(read.magic,"CAPISTOR",8)||read.size!=bytes.size()||read.crc!=crc32(check.data(),check.size()))return false;
  nvs_handle_t handle; if(nvs_open("capi",NVS_READWRITE,&handle)!=ESP_OK)return false; esp_err_t result=nvs_set_u8(handle,"slot",slot); if(result==ESP_OK)result=nvs_commit(handle); nvs_close(handle); return result==ESP_OK;
}
static bool load_rules() {
  const esp_partition_t *partition=rules_partition(active_slot()); StoredRules header{}; if(!partition||esp_partition_read(partition,0,&header,sizeof(header))!=ESP_OK||memcmp(header.magic,"CAPISTOR",8)||!header.size||header.size>MAX_RULES||header.size+sizeof(header)>partition->size)return false;
  std::vector<uint8_t> bytes(header.size); if(esp_partition_read(partition,sizeof(header),bytes.data(),bytes.size())!=ESP_OK||crc32(bytes.data(),bytes.size())!=header.crc)return false;
  cJSON *parsed=nullptr; if(!validate_rules(bytes,&parsed))return false; cJSON_Delete(active); active=parsed; return true;
}

static bool condition(cJSON *value) {
  const char *kind = text(value, "kind");
  if (!strcmp(kind, "boolean")) return cJSON_IsTrue(cJSON_GetObjectItem(value, "value"));
  if (!strcmp(kind, "counter")) { int right = number(value, "value"), left = counter_value; const char *op = text(value, "operator"); return !strcmp(op,"EQ") ? left==right : !strcmp(op,"NEQ") ? left!=right : !strcmp(op,"LT") ? left<right : !strcmp(op,"LTE") ? left<=right : !strcmp(op,"GT") ? left>right : left>=right; }
  if (!strcmp(kind, "compare")) { int right=number(value,"right"),left=number(value,"left");const char *op=text(value,"operator");return !strcmp(op,"EQ")?left==right:!strcmp(op,"NEQ")?left!=right:!strcmp(op,"LT")?left<right:!strcmp(op,"LTE")?left<=right:!strcmp(op,"GT")?left>right:left>=right; }
  if (!strcmp(kind, "sensor")) { cJSON *dev=device(text(value,"deviceId"));int left=analog_read(pin(dev,"signal")),right=number(value,"value");const char *op=text(value,"operator");return !strcmp(op,"LT")?left<right:!strcmp(op,"LTE")?left<=right:!strcmp(op,"GT")?left>right:left>=right; }
  if (!strcmp(kind, "buttonPressed")) { cJSON *dev = device(text(value,"deviceId")); int gpio = pin(dev,"signal"); if (gpio < 0) return false; gpio_set_direction((gpio_num_t)gpio, GPIO_MODE_INPUT); cJSON *config=cJSON_GetObjectItem(dev,"config"); gpio_set_pull_mode((gpio_num_t)gpio,cJSON_IsTrue(config?cJSON_GetObjectItem(config,"pullup"):nullptr)?GPIO_PULLUP_ONLY:GPIO_FLOATING); return gpio_get_level((gpio_num_t)gpio) == 0; }
  if (!strcmp(kind,"value")) return value_boolean(evaluate(cJSON_GetObjectItem(value,"expression")));
  if (!strcmp(kind,"valueCompare")) {RuntimeValue left=evaluate(cJSON_GetObjectItem(value,"left")),right=evaluate(cJSON_GetObjectItem(value,"right"));const char *op=text(value,"operator");if(!strcmp(op,"EQ")||!strcmp(op,"NEQ")){bool same=left.kind==right.kind&&(left.kind==RuntimeValue::TEXT?left.text==right.text:left.kind==RuntimeValue::BOOLEAN?left.boolean==right.boolean:left.number==right.number);return !strcmp(op,"EQ")?same:!same;}int32_t a=value_number(left),b=value_number(right);return !strcmp(op,"LT")?a<b:!strcmp(op,"LTE")?a<=b:!strcmp(op,"GT")?a>b:a>=b;}
  return false;
}
struct TaskContext { cJSON *task; int index; };
static void execute_task(void *parameter);
static bool start_task(int index) {
  if(!running||index<0||index>=32)return false; int expected=0;if(!task_states[index].compare_exchange_strong(expected,1))return expected==1||expected==2;
  cJSON *tasks=cJSON_GetObjectItem(active,"tasks"),*task=cJSON_GetArrayItem(tasks,index);if(!task){task_states[index]=0;return false;}
  TaskContext *context=new(std::nothrow) TaskContext{task,index};if(!context){task_states[index]=0;return false;}++active_tasks;
  char name[16];snprintf(name,sizeof(name),"capi-%d",index);if(xTaskCreate(execute_task,name,6144,context,5,nullptr)!=pdPASS){--active_tasks;task_states[index]=0;delete context;return false;}return true;
}
static void execute_task(void *parameter) {
  TaskContext *context=(TaskContext*)parameter;cJSON *task=context->task,*instructions=cJSON_GetObjectItem(task,"output");int task_index=context->index;delete context;int pc=0,reported=-1;std::vector<int> loops(32,0);bool message_waiting=false,otto_waiting=false;TickType_t message_started=0,otto_started=0;
  while (running && pc < cJSON_GetArraySize(instructions)) {
    while (paused && running) vTaskDelay(pdMS_TO_TICKS(20)); if (!running) break;
    cJSON *instruction = cJSON_GetArrayItem(instructions, pc), *dev = device(text(instruction,"deviceId")); const char *op = text(instruction,"op"), *block = text(instruction,"blockId",nullptr);
    if(reported!=pc){telemetry("block",block,op);reported=pc;}
    if (!strcmp(op,"halt")) break;
    if (!strcmp(op,"wait")) vTaskDelay(pdMS_TO_TICKS(std::max(0, number(instruction,"ms"))));
    else if (!strcmp(op,"counterSet")) {counter_value=number(instruction,"value");telemetry_state("counter",block,nullptr,std::to_string(counter_value.load()));}
    else if (!strcmp(op,"counterChange")) {counter_value.fetch_add(number(instruction,"delta"));telemetry_state("counter",block,nullptr,std::to_string(counter_value.load()));}
    else if (!strcmp(op,"variableSet")||!strcmp(op,"variableChange")) {const char *id=text(instruction,"variableId");RuntimeValue incoming=evaluate(cJSON_GetObjectItem(instruction,!strcmp(op,"variableSet")?"value":"delta"));std::string shown;if(variables_mutex)xSemaphoreTake(variables_mutex,portMAX_DELAY);for(auto &variable:variables)if(variable.id==id){if(!strcmp(op,"variableChange")&&variable.value.kind==RuntimeValue::NUMBER){int64_t result=(int64_t)variable.value.number+value_number(incoming);variable.value.number=(int32_t)std::clamp<int64_t>(result,INT32_MIN,INT32_MAX);}else if(variable.value.kind==RuntimeValue::TEXT)variable.value.text=value_text(incoming);else if(variable.value.kind==RuntimeValue::BOOLEAN)variable.value.boolean=value_boolean(incoming);else variable.value.number=value_number(incoming);shown=value_text(variable.value);break;}if(variables_mutex)xSemaphoreGive(variables_mutex);telemetry_state("variable",block,id,shown);}
    else if (!strcmp(op,"pin")) output(number(instruction,"pin",-1), cJSON_IsTrue(cJSON_GetObjectItem(instruction,"value")));
    else if (!strcmp(op,"led")) {int brightness=number(instruction,"brightness");pwm(pin(dev,"signal"),brightness);telemetry_state("device",block,text(instruction,"deviceId"),std::to_string(brightness));}
    else if (!strcmp(op,"traffic")) { const char *color=text(instruction,"color");cJSON *config=cJSON_GetObjectItem(dev,"config");pwm(pin(dev,"red"),!strcmp(color,"RED")?number(config,"redBrightness",100):0);pwm(pin(dev,"yellow"),!strcmp(color,"YELLOW")?number(config,"yellowBrightness",100):0);pwm(pin(dev,"green"),!strcmp(color,"GREEN")?number(config,"greenBrightness",100):0); }
    else if (!strcmp(op,"motor")) { const char *direction=text(instruction,"direction");int power=number(instruction,"power");motor(dev,!strcmp(direction,"FORWARD")?power:!strcmp(direction,"BACKWARD")?-power:0); }
    else if (!strcmp(op,"robot")) { const char *action=text(instruction,"action");int speed=number(instruction,"speed");int left=!strcmp(action,"BACKWARD")?-speed:!strcmp(action,"LEFT")?-speed:!strcmp(action,"STOP")?0:speed;int right=!strcmp(action,"BACKWARD")?-speed:!strcmp(action,"RIGHT")?-speed:!strcmp(action,"STOP")?0:speed;motor(dev,left,true,false);motor(dev,right,true,true); }
    else if (!strcmp(op,"otto")) {const char *action=text(instruction,"action");if(!strcmp(action,"HOME")){if(otto_mutex)xSemaphoreTake(otto_mutex,portMAX_DELAY);otto.owner=-1;otto_home();if(otto_mutex)xSemaphoreGive(otto_mutex);otto_waiting=false;}else{static const char *actions[]={"WALK_FORWARD","WALK_BACKWARD","TURN_LEFT","TURN_RIGHT","DANCE","JUMP","SWING","TIPTOE","JITTER","MOONWALK_LEFT","MOONWALK_RIGHT","BEND_LEFT","BEND_RIGHT","SHAKE_LEFT","SHAKE_RIGHT","FLAP_FORWARD","FLAP_BACKWARD"};int action_index=0;for(int i=0;i<17;++i)if(!strcmp(action,actions[i]))action_index=i;int step_ms=480-std::clamp(number(instruction,"speed",60),0,100)*3,duration=step_ms*4*std::clamp(number(instruction,"repetitions",1),1,20);if(!otto_waiting){int expected=-1;if(!otto.owner.compare_exchange_strong(expected,task_index)){vTaskDelay(pdMS_TO_TICKS(5));continue;}otto_started=xTaskGetTickCount();otto_waiting=true;}if(otto.owner!=task_index){otto_waiting=false;continue;}uint32_t elapsed=(xTaskGetTickCount()-otto_started)*portTICK_PERIOD_MS;if(otto_mutex)xSemaphoreTake(otto_mutex,portMAX_DELAY);otto_move(action_index,(elapsed/step_ms)%4);if(otto_mutex)xSemaphoreGive(otto_mutex);if(elapsed<(uint32_t)duration){vTaskDelay(pdMS_TO_TICKS(5));continue;}if(otto_mutex)xSemaphoreTake(otto_mutex,portMAX_DELAY);otto_home();otto.owner=-1;if(otto_mutex)xSemaphoreGive(otto_mutex);otto_waiting=false;}}
    else if (!strcmp(op,"ottoSound")) {static const char *sounds[]={"HAPPY","SAD","SURPRISE","CONFUSED","SLEEPING","BUTTON","MODE","FART"};int selected=0;for(int i=0;i<8;++i)if(!strcmp(text(instruction,"sound"),sounds[i]))selected=i;if(otto_mutex)xSemaphoreTake(otto_mutex,portMAX_DELAY);otto_sound(selected);if(otto_mutex)xSemaphoreGive(otto_mutex);}
    else if (!strcmp(op,"ottoExpression")) {static const char *expressions[]={"SMILE","SAD","ANGRY","SURPRISED","SLEEPY","LOVE","CLEAR"};int selected=6;for(int i=0;i<7;++i)if(!strcmp(text(instruction,"expression"),expressions[i]))selected=i;if(otto_mutex)xSemaphoreTake(otto_mutex,portMAX_DELAY);otto_expression(selected);if(otto_mutex)xSemaphoreGive(otto_mutex);}
    else if (!strcmp(op,"ottoArms")) {static const char *poses[]={"DOWN","UP","LEFT_UP","RIGHT_UP","OPEN"};int selected=0;for(int i=0;i<5;++i)if(!strcmp(text(instruction,"pose"),poses[i]))selected=i;if(otto_mutex)xSemaphoreTake(otto_mutex,portMAX_DELAY);otto_arms(selected);if(otto_mutex)xSemaphoreGive(otto_mutex);}
    else if (!strcmp(op,"servo")) servo(pin(dev,"signal"),number(instruction,"angle"));
    else if (!strcmp(op,"buzzer")) buzzer(dev,!strcmp(text(instruction,"kind"),"ACTIVE"),number(instruction,"frequency",880),number(instruction,"durationMs"));
    else if (!strcmp(op,"tone")) buzzer(dev,false,number(instruction,"frequency",440),number(instruction,"durationMs"));
    else if (!strcmp(op,"serial")) {cJSON *expression=cJSON_GetObjectItem(instruction,"expression");std::string message=expression?value_text(evaluate(expression)):text(instruction,"text");telemetry("message",block,message.c_str());}
    else if (!strcmp(op,"messageSend")) {cJSON *expression=cJSON_GetObjectItem(instruction,"expression");std::string message=expression?value_text(evaluate(expression)):text(instruction,"text");bool sent=false;if(message_mutex)xSemaphoreTake(message_mutex,portMAX_DELAY);sent=message_send(message);if(message_mutex)xSemaphoreGive(message_mutex);if(!sent)telemetry("warning",block,"No se pudo enviar el mensaje.");else telemetry_state("message-sent",block,text(instruction,"deviceId"),message);}
    else if (!strcmp(op,"messageReceiveWait")) {if(!message_waiting){message_waiting=true;message_started=xTaskGetTickCount();}char received[121]={};int result=0;if(message_mutex)xSemaphoreTake(message_mutex,portMAX_DELAY);result=message_poll(received);if(result==1)message_last=received;if(message_mutex)xSemaphoreGive(message_mutex);if(result==1){message_waiting=false;telemetry_state("message-received",block,text(instruction,"deviceId"),received);pc=!strcmp(received,text(instruction,"expected"))?number(instruction,"equalTarget"):number(instruction,"differentTarget");continue;}if((uint32_t)((xTaskGetTickCount()-message_started)*portTICK_PERIOD_MS)>=(uint32_t)number(instruction,"timeoutMs")){message_waiting=false;pc=number(instruction,"timeoutTarget");continue;}vTaskDelay(pdMS_TO_TICKS(5));continue;}
    else if (!strcmp(op,"matrixClear")) {if(matrix_mutex)xSemaphoreTake(matrix_mutex,portMAX_DELAY);matrix.active=false;memset(matrix.rows,0,sizeof(matrix.rows));matrix_flush();if(matrix_mutex)xSemaphoreGive(matrix_mutex);}
    else if (!strcmp(op,"matrixPixel")) {if(matrix_mutex)xSemaphoreTake(matrix_mutex,portMAX_DELAY);matrix.active=false;int x=std::clamp(number(instruction,"x"),0,31),y=std::clamp(number(instruction,"y"),0,7);uint32_t mask=1UL<<(31-x);if(cJSON_IsTrue(cJSON_GetObjectItem(instruction,"enabled")))matrix.rows[y]|=mask;else matrix.rows[y]&=~mask;matrix_flush();if(matrix_mutex)xSemaphoreGive(matrix_mutex);}
    else if (!strcmp(op,"matrixPattern")) {if(matrix_mutex)xSemaphoreTake(matrix_mutex,portMAX_DELAY);matrix.active=false;cJSON *config=cJSON_GetObjectItem(dev,"config"),*patterns=config?cJSON_GetObjectItem(config,"patterns"):nullptr,*pattern;cJSON_ArrayForEach(pattern,patterns)if(!strcmp(text(pattern,"id"),text(instruction,"patternId"))){cJSON *rows=cJSON_GetObjectItem(pattern,"rows");for(int row=0;row<8;++row){cJSON *value=cJSON_GetArrayItem(rows,row);matrix.rows[row]=cJSON_IsNumber(value)?(uint32_t)value->valuedouble:0;}break;}matrix_flush();if(matrix_mutex)xSemaphoreGive(matrix_mutex);}
    else if (!strcmp(op,"matrixScroll")) {if(matrix_mutex)xSemaphoreTake(matrix_mutex,portMAX_DELAY);matrix.text=text(instruction,"text");if(matrix.text.size()>32)matrix.text.resize(32);matrix.speed=std::clamp(number(instruction,"speedMs",100),20,2000);matrix.repeats=std::clamp(number(instruction,"repeatCount",1),0,100);matrix.offset=0;matrix.next=xTaskGetTickCount();matrix.active=true;if(matrix_mutex)xSemaphoreGive(matrix_mutex);}
    else if (!strcmp(op,"visualWait")) {bool active=false;if(matrix_mutex)xSemaphoreTake(matrix_mutex,portMAX_DELAY);active=matrix.active;if(matrix_mutex)xSemaphoreGive(matrix_mutex);if(active){vTaskDelay(pdMS_TO_TICKS(5));continue;}}
    else if (!strcmp(op,"repeatStart")) { int slot=number(instruction,"slot"), count=number(instruction,"count"); if (slot>=0&&slot<(int)loops.size()) { if (!loops[slot]) loops[slot]=count; if (loops[slot]<=0) { loops[slot]=0; pc=number(instruction,"end"); continue; } } }
    else if (!strcmp(op,"repeatNext")) { int slot=number(instruction,"slot"); if(slot>=0&&slot<(int)loops.size()&&--loops[slot]>0){pc=number(instruction,"target");continue;} }
    else if (!strcmp(op,"fork")) { cJSON *children=cJSON_GetObjectItem(instruction,"children"),*child;cJSON_ArrayForEach(child,children)if(cJSON_IsNumber(child))start_task(child->valueint); }
    else if (!strcmp(op,"join")) { bool ready=true;cJSON *children=cJSON_GetObjectItem(instruction,"children"),*child;cJSON_ArrayForEach(child,children)if(cJSON_IsNumber(child)&&(child->valueint<0||child->valueint>=32||task_states[child->valueint]!=2))ready=false;if(!ready){vTaskDelay(pdMS_TO_TICKS(5));continue;} }
    else if (!strcmp(op,"jump")) { pc=number(instruction,"target"); continue; }
    else if (!strcmp(op,"jumpIfFalse") && !condition(cJSON_GetObjectItem(instruction,"condition"))) { pc=number(instruction,"target"); continue; }
    ++pc; taskYIELD();
  }
  task_states[task_index]=2;telemetry("task-done",text(task,"id"),"Camino terminado");if(--active_tasks==0){running=false;telemetry("program-done",nullptr,"Programa terminado");}vTaskDelete(nullptr);
}
static bool start_program() { if(!active||running||active_tasks>0)return false;for(auto &state:task_states)state=0;counter_value=0;initialize_variables();if(message_mutex)xSemaphoreTake(message_mutex,portMAX_DELAY);message_last.clear();bool messages_ready=message_begin();if(message_mutex)xSemaphoreGive(message_mutex);if(!messages_ready){telemetry("error",nullptr,"No se pudo iniciar el puerto de Mensajes.");return false;}if(matrix_mutex)xSemaphoreTake(matrix_mutex,portMAX_DELAY);matrix_begin();if(matrix_mutex)xSemaphoreGive(matrix_mutex);if(otto_mutex)xSemaphoreTake(otto_mutex,portMAX_DELAY);otto_begin();if(otto_mutex)xSemaphoreGive(otto_mutex);running=true;paused=false;cJSON *tasks=cJSON_GetObjectItem(active,"tasks"),*task;int index=0,started=0;cJSON_ArrayForEach(task,tasks){if(cJSON_IsTrue(cJSON_GetObjectItem(task,"initial"))&&start_task(index))++started;++index;}if(!started){running=false;return false;}return true; }

static void command(cJSON *request) {
  const char *type = text(request,"type");
  if (!strcmp(type,"HELLO")) { cJSON *out=cJSON_CreateObject(); cJSON_AddStringToObject(out,"type","HELLO"); cJSON_AddStringToObject(out,"protocol","CapiLink"); cJSON_AddStringToObject(out,"firmware",CAPI_FIRMWARE_VERSION); cJSON_AddNumberToObject(out,"abi",ABI); cJSON_AddStringToObject(out,"board",CAPI_BOARD_ID); cJSON_AddNumberToObject(out,"maxRulesBytes",MAX_RULES); cJSON *caps=cJSON_AddArrayToObject(out,"capabilities"); for(const char *cap:{"core","parallel","expressions","variables","gpio","led","traffic","motor","robot","otto","servo","buzzer","matrix","visual-wait","messages","counter","serial","digital-input","analog-input"}) cJSON_AddItemToArray(caps,cJSON_CreateString(cap)); cJSON *resources=cJSON_AddObjectToObject(out,"resources");cJSON_AddNumberToObject(resources,"pwmChannels",8); send_json(out); }
  else if (!strcmp(type,"BEGIN")) { if(running){reply("ERROR","Detené el programa antes de reemplazarlo.");return;} expected_bytes=number(request,"bytes"); const char *sum=text(request,"checksum"); expected_crc=strtoul(sum,nullptr,16); if(!expected_bytes||expected_bytes>MAX_RULES){reply("ERROR","Tamaño de reglas inválido.");return;} candidate.clear(); candidate.reserve(expected_bytes); reply("READY"); }
  else if (!strcmp(type,"CHUNK")) { const char *encoded=text(request,"data"); size_t capacity=strlen(encoded)*3/4+3, written=0, before=candidate.size(); candidate.resize(before+capacity); if(mbedtls_base64_decode(candidate.data()+before,capacity,&written,(const unsigned char*)encoded,strlen(encoded))!=0||before+written>expected_bytes){candidate.clear();reply("ERROR","Fragmento inválido.");return;} candidate.resize(before+written); reply("ACK"); }
  else if (!strcmp(type,"VERIFY")) { cJSON *parsed=nullptr; if(candidate.size()!=expected_bytes||candidate.size()<32||crc32(candidate.data()+32,candidate.size()-32)!=expected_crc||!validate_rules(candidate,&parsed)){reply("ERROR","Las reglas no superaron la verificación.");return;} cJSON_Delete(parsed); reply("VERIFIED"); }
  else if (!strcmp(type,"COMMIT")) { cJSON *parsed=nullptr; if(!validate_rules(candidate,&parsed)||!persist(candidate)){cJSON_Delete(parsed);reply("ERROR","No pudimos guardar las reglas.");return;} running=false; cJSON_Delete(active); active=parsed; candidate.clear(); reply("COMMITTED"); }
  else if (!strcmp(type,"RUN")) { if(start_program()) reply("OK"); else reply("ERROR","No hay reglas o el programa ya está ejecutándose."); }
  else if (!strcmp(type,"PAUSE")) { paused=true; reply("OK"); }
  else if (!strcmp(type,"RESUME")) { paused=false; reply("OK"); }
  else if (!strcmp(type,"STOP")) { running=false; paused=false; for(int attempt=0;active_tasks>0&&attempt<100;++attempt)vTaskDelay(pdMS_TO_TICKS(10)); safe_outputs(); reply(active_tasks==0?"OK":"ERROR",active_tasks==0?nullptr:"No pudimos detener todos los caminos."); }
  else if (!strcmp(type,"RESET_PROGRAM")) { running=false; paused=false; counter_value=0; safe_outputs(); reply("OK"); }
  else reply("ERROR","Comando desconocido.");
}

extern "C" void app_main() {
  nvs_flash_init();variables_mutex=xSemaphoreCreateMutex();matrix_mutex=xSemaphoreCreateMutex();message_mutex=xSemaphoreCreateMutex();otto_mutex=xSemaphoreCreateMutex();xTaskCreate(matrix_service,"capi-matrix",3072,nullptr,3,nullptr);xTaskCreate(otto_service,"capi-otto",3072,nullptr,3,nullptr);uart_driver_install(LINK,8192,0,0,nullptr,0); uart_config_t config={}; config.baud_rate=115200; config.data_bits=UART_DATA_8_BITS; config.parity=UART_PARITY_DISABLE; config.stop_bits=UART_STOP_BITS_1; config.flow_ctrl=UART_HW_FLOWCTRL_DISABLE; config.source_clk=UART_SCLK_DEFAULT; uart_param_config(LINK,&config); if(load_rules()) start_program();
  std::string line; uint8_t byte;
  for(;;){ if(uart_read_bytes(LINK,&byte,1,pdMS_TO_TICKS(100))!=1) continue; if(byte=='\n'){ if(!line.empty()&&line.size()<32768){ cJSON *request=cJSON_ParseWithLength(line.data(),line.size()); if(request){command(request);cJSON_Delete(request);} else reply("ERROR","Mensaje inválido."); } line.clear(); } else if(byte!='\r'&&line.size()<32768) line.push_back((char)byte); }
}
