# Generated by Django 5.2.17 on 2026-09-08 02:56

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompilerConfig',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('concurrency', models.PositiveSmallIntegerField(default=1)),
                ('ceiling', models.PositiveSmallIntegerField(default=1)),
                ('paused', models.BooleanField(default=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('recipe', models.CharField(blank=True, max_length=64)),
                ('runner_seen', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompilerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_id_snapshot', models.UUIDField(null=True)),
                ('before', models.JSONField()),
                ('after', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_id_snapshot', models.UUIDField(db_index=True)),
                ('project_id_snapshot', models.UUIDField(db_index=True)),
                ('project_revision', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=80)),
                ('framework', models.CharField(max_length=10)),
                ('recipe', models.CharField(max_length=64)),
                ('request_digest', models.CharField(max_length=64)),
                ('cache_key', models.CharField(max_length=64)),
                ('document', models.JSONField(null=True)),
                ('wifi_encrypted', models.TextField(blank=True)),
                ('contains_wifi', models.BooleanField(default=False)),
                ('state', models.CharField(db_index=True, default='queued', max_length=12)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('expires_at', models.DateTimeField()),
                ('attempt', models.UUIDField(null=True)),
                ('lease_until', models.DateTimeField(null=True)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('artifact', models.UUIDField(null=True)),
                ('artifact_sha256', models.CharField(blank=True, max_length=64)),
                ('artifact_bytes', models.PositiveIntegerField(default=0)),
                ('message', models.CharField(blank=True, max_length=200)),
                ('metrics', models.JSONField(default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'created_at'], name='build_queue_order')],
            },
        ),
    ]

