import type { PinCapability, PinNumber } from './scene-model.ts';

export const educationalModuleKinds = [
  'distanceSensor', 'pirSensor', 'joystick', 'powerSwitch', 'rotaryEncoder',
  'environmentSensor', 'soilMoisture', 'colorSensor', 'soundLevel', 'waterSensor',
  'motionSensor', 'cardReader', 'keypad',
  'stepper', 'scale', 'gps',
] as const;

export type EducationalModuleKind = (typeof educationalModuleKinds)[number];
export type ModuleValueType = 'number' | 'text' | 'boolean';
export interface ModuleValueSpec { key: string; label: string; type: ModuleValueType; min?: number; max?: number; step?: number; unit?: string; choices?: string[]; help: string }
export interface ModulePinSpec { key: string; label: string; capability: PinCapability; optional?: boolean }
export interface EducationalModuleSpec {
  kind: EducationalModuleKind; phase: 38 | 39 | 40 | 41; icon: string; name: string; description: string;
  profiles: readonly { id: string; label: string }[]; pins: readonly ModulePinSpec[]; values: readonly ModuleValueSpec[];
  defaults: { profile: string; values: Record<string, number | string | boolean>; settings: Record<string, number | string | boolean> };
  needs: readonly string[]; cautions: readonly string[];
}

const n = (key: string, label: string, min: number, max: number, unit: string, help: string, step = 1): ModuleValueSpec => ({ key, label, type: 'number', min, max, step, unit, help });
const b = (key: string, label: string, help: string): ModuleValueSpec => ({ key, label, type: 'boolean', help });
const t = (key: string, label: string, help: string, choices?: string[]): ModuleValueSpec => ({ key, label, type: 'text', help, choices });
const pin = (key: string, label: string, capability: PinCapability, optional = false): ModulePinSpec => ({ key, label, capability, optional });

export const educationalModuleSpecs: Record<EducationalModuleKind, EducationalModuleSpec> = {
  distanceSensor: { kind:'distanceSensor', phase:38, icon:'📏', name:'Sensor de distancia', description:'Mide qué tan lejos está un objeto.', profiles:[{id:'HC-SR04',label:'HC-SR04 (ultrasonido)'},{id:'VL53L0X',label:'VL53L0X (láser seguro)'}], pins:[pin('trigger','TRIG / SDA','pwmOutput'),pin('echo','ECHO / SCL','digitalInput')], values:[n('distance','distancia',0,500,'cm','Distancia medida por el sensor.')], defaults:{profile:'HC-SR04',values:{distance:30},settings:{maxDistance:400}}, needs:['Sensor HC-SR04 o VL53L0X','Cables'], cautions:['No tapes el emisor ni el receptor.'] },
  pirSensor: { kind:'pirSensor', phase:38, icon:'👋', name:'Sensor de movimiento', description:'Detecta movimiento de personas con un PIR.', profiles:[{id:'HC-SR501',label:'HC-SR501'}], pins:[pin('signal','Señal','digitalInput')], values:[b('motion','hay movimiento','Indica si el PIR detectó movimiento.')], defaults:{profile:'HC-SR501',values:{motion:false},settings:{}}, needs:['Módulo PIR'], cautions:['Puede tardar unos segundos en estabilizarse.'] },
  joystick: { kind:'joystick', phase:38, icon:'🕹️', name:'Palanca', description:'Palanca de dos ejes con botón.', profiles:[{id:'KY-023',label:'Joystick KY-023'}], pins:[pin('x','Eje X','analogInput'),pin('y','Eje Y','analogInput'),pin('button','Botón','digitalInput')], values:[n('x','posición X',0,4095,'','Posición horizontal.'),n('y','posición Y',0,4095,'','Posición vertical.'),b('pressed','botón presionado','Lee el botón de la palanca.')], defaults:{profile:'KY-023',values:{x:2048,y:2048,pressed:false},settings:{deadZone:180}}, needs:['Joystick analógico'], cautions:['El centro real puede variar un poco.'] },
  powerSwitch: { kind:'powerSwitch', phase:38, icon:'🔌', name:'Interruptor de potencia', description:'Controla una carga de baja tensión mediante MOSFET o relé.', profiles:[{id:'MOSFET',label:'MOSFET (potencia regulable)'},{id:'RELAY_LOW_VOLTAGE',label:'Relé de baja tensión'}], pins:[pin('signal','Control','pwmOutput')], values:[n('power','potencia ordenada',0,100,'%','Potencia que pidió el programa.')], defaults:{profile:'MOSFET',values:{power:0},settings:{activeHigh:true}}, needs:['Módulo MOSFET o relé de baja tensión'], cautions:['Sólo baja tensión; nunca conectar la red eléctrica.'] },
  rotaryEncoder: { kind:'rotaryEncoder', phase:38, icon:'🎛️', name:'Perilla giratoria', description:'Cuenta giros y también funciona como botón.', profiles:[{id:'KY-040',label:'Encoder KY-040'}], pins:[pin('a','Canal A','digitalInput'),pin('b','Canal B','digitalInput'),pin('button','Botón','digitalInput')], values:[n('position','posición',-10000,10000,'','Cuenta pasos hacia ambos lados.'),b('pressed','botón presionado','Lee el botón del encoder.')], defaults:{profile:'KY-040',values:{position:0,pressed:false},settings:{step:1}}, needs:['Encoder rotativo'], cautions:['Un giro rápido puede producir varios pasos.'] },
  environmentSensor: { kind:'environmentSensor', phase:39, icon:'🌦️', name:'Clima', description:'Mide temperatura, humedad y presión.', profiles:[{id:'BME280',label:'BME280 I²C'}], pins:[pin('sda','SDA','pwmOutput'),pin('scl','SCL','pwmOutput')], values:[n('temperature','temperatura',-40,85,'°C','Temperatura ambiente.',0.1),n('humidity','humedad',0,100,'%','Humedad relativa.',0.1),n('pressure','presión',300,1100,'hPa','Presión atmosférica.',0.1)], defaults:{profile:'BME280',values:{temperature:22,humidity:50,pressure:1013},settings:{address:118}}, needs:['BME280'], cautions:['Evitá tocarlo durante la medición.'] },
  soilMoisture: { kind:'soilMoisture', phase:39, icon:'🌱', name:'Humedad de tierra', description:'Estima cuánta agua tiene la tierra.', profiles:[{id:'CAPACITIVE_V1',label:'Capacitivo analógico'}], pins:[pin('signal','Salida analógica','analogInput')], values:[n('moisture','humedad',0,100,'%','Humedad calculada con la calibración.')], defaults:{profile:'CAPACITIVE_V1',values:{moisture:50},settings:{dry:3000,wet:1300}}, needs:['Sensor capacitivo'], cautions:['Calibralo primero en seco y húmedo.'] },
  colorSensor: { kind:'colorSensor', phase:39, icon:'🎨', name:'Sensor de color', description:'Mide luz roja, verde, azul y brillo.', profiles:[{id:'TCS34725',label:'TCS34725 I²C'}], pins:[pin('sda','SDA','pwmOutput'),pin('scl','SCL','pwmOutput')], values:[n('red','rojo',0,255,'','Cantidad de rojo.'),n('green','verde',0,255,'','Cantidad de verde.'),n('blue','azul',0,255,'','Cantidad de azul.'),n('light','luz',0,100,'%','Brillo aproximado.')], defaults:{profile:'TCS34725',values:{red:255,green:80,blue:40,light:60},settings:{address:41}}, needs:['TCS34725'], cautions:['La luz ambiente cambia la lectura.'] },
  soundLevel: { kind:'soundLevel', phase:39, icon:'🎙️', name:'Nivel de sonido', description:'Mide intensidad; no graba conversaciones.', profiles:[{id:'ANALOG_MIC',label:'Micrófono analógico'}], pins:[pin('signal','Nivel analógico','analogInput')], values:[n('level','nivel',0,100,'%','Intensidad aproximada.'),b('loud','sonido fuerte','Compara el nivel con el umbral.')], defaults:{profile:'ANALOG_MIC',values:{level:20,loud:false},settings:{threshold:65}}, needs:['Módulo de micrófono analógico'], cautions:['Sólo mide volumen; no almacena audio.'] },
  waterSensor: { kind:'waterSensor', phase:39, icon:'💧', name:'Agua y lluvia', description:'Detecta agua o lluvia y estima su nivel.', profiles:[{id:'ANALOG_WATER',label:'Placa analógica de agua/lluvia'}], pins:[pin('signal','Salida analógica','analogInput')], values:[n('level','nivel',0,100,'%','Cantidad aproximada de agua.'),b('wet','está mojado','Compara el nivel con el umbral.')], defaults:{profile:'ANALOG_WATER',values:{level:0,wet:false},settings:{threshold:20}}, needs:['Sensor de agua o lluvia'], cautions:['Secalo luego de usarlo para evitar corrosión.'] },
  motionSensor: { kind:'motionSensor', phase:40, icon:'🧭', name:'Movimiento y orientación', description:'Mide aceleración e inclinación.', profiles:[{id:'MPU6050',label:'MPU6050 I²C'}], pins:[pin('sda','SDA','pwmOutput'),pin('scl','SCL','pwmOutput')], values:[n('x','inclinación X',-180,180,'°','Inclinación lateral.'),n('y','inclinación Y',-180,180,'°','Inclinación frontal.'),n('z','aceleración Z',-4,4,'g','Aceleración vertical.',0.01),b('moving','se está moviendo','Indica movimiento apreciable.')], defaults:{profile:'MPU6050',values:{x:0,y:0,z:1,moving:false},settings:{sensitivity:10}}, needs:['MPU6050'], cautions:['Calibralo quieto sobre una mesa.'] },
  cardReader: { kind:'cardReader', phase:40, icon:'💳', name:'Lector de tarjetas', description:'Reconoce tarjetas configuradas por un nombre amigable.', profiles:[{id:'PN532',label:'PN532 I²C'}], pins:[pin('sda','SDA','pwmOutput'),pin('scl','SCL','pwmOutput')], values:[t('card','tarjeta reconocida','Nombre amigable de la última tarjeta.', ['ninguna','azul','roja','docente']),b('present','hay una tarjeta','Indica si hay una tarjeta cerca.')], defaults:{profile:'PN532',values:{card:'ninguna',present:false},settings:{}}, needs:['PN532 y tarjetas compatibles'], cautions:['La aplicación usa alias, no muestra identificadores sensibles.'] },
  keypad: { kind:'keypad', phase:40, icon:'🔢', name:'Teclado de botones', description:'Lee teclas de una matriz 3×4 o 4×4.', profiles:[{id:'KEYPAD_4X4',label:'Teclado 4×4'},{id:'KEYPAD_3X4',label:'Teclado 3×4'}], pins:[pin('r1','Fila 1','digitalInput'),pin('r2','Fila 2','digitalInput'),pin('r3','Fila 3','digitalInput'),pin('r4','Fila 4','digitalInput'),pin('c1','Columna 1','pwmOutput'),pin('c2','Columna 2','pwmOutput'),pin('c3','Columna 3','pwmOutput'),pin('c4','Columna 4','pwmOutput',true)], values:[t('key','última tecla','Tecla presionada.', ['','1','2','3','4','5','6','7','8','9','0','A','B','C','D','*','#']),b('pressed','hay una tecla presionada','Indica si alguna tecla está activa.')], defaults:{profile:'KEYPAD_4X4',values:{key:'',pressed:false},settings:{}}, needs:['Teclado matricial'], cautions:['No compartas sus pines con otros componentes.'] },
  stepper: { kind:'stepper', phase:41, icon:'⚙️', name:'Motor paso a paso', description:'Mueve un 28BYJ-48 mediante ULN2003.', profiles:[{id:'28BYJ-48_ULN2003',label:'28BYJ-48 + ULN2003'}], pins:[pin('in1','IN1','pwmOutput'),pin('in2','IN2','pwmOutput'),pin('in3','IN3','pwmOutput'),pin('in4','IN4','pwmOutput')], values:[n('position','posición ordenada',-1000000,1000000,' pasos','Posición pedida por el programa.'),b('moving','se está moviendo','Indica si todavía quedan pasos.')], defaults:{profile:'28BYJ-48_ULN2003',values:{position:0,moving:false},settings:{speed:300}}, needs:['Motor 28BYJ-48','Placa ULN2003','Fuente adecuada'], cautions:['No conectes el motor directamente a los GPIO.'] },
  scale: { kind:'scale', phase:41, icon:'⚖️', name:'Balanza', description:'Mide peso con una celda de carga y HX711.', profiles:[{id:'HX711',label:'HX711 + celda de carga'}], pins:[pin('data','Datos','digitalInput'),pin('clock','Reloj','pwmOutput')], values:[n('weight','peso',-10000,10000,'g','Peso luego de aplicar tara y calibración.',0.1)], defaults:{profile:'HX711',values:{weight:0},settings:{factor:1,tare:0}}, needs:['HX711','Celda de carga'], cautions:['Calibrala con un peso conocido.'] },
  gps: { kind:'gps', phase:41, icon:'🛰️', name:'Ubicación GPS', description:'Lee posición y velocidad desde un receptor GPS.', profiles:[{id:'NMEA_UART',label:'GPS NMEA por RX/TX'}], pins:[pin('rx','Recibir del GPS','digitalInput'),pin('tx','Enviar al GPS','pwmOutput',true)], values:[n('latitude','latitud',-90,90,'°','Latitud en grados.',0.000001),n('longitude','longitud',-180,180,'°','Longitud en grados.',0.000001),n('speed','velocidad',0,1000,'km/h','Velocidad informada.',0.1),b('signal','tiene señal','Indica si la posición es válida.')], defaults:{profile:'NMEA_UART',values:{latitude:-34.6037,longitude:-58.3816,speed:0,signal:false},settings:{baudRate:9600}}, needs:['Receptor GPS NMEA'], cautions:['Usá recorridos ficticios en clase para cuidar la privacidad.'] },
};

export function isEducationalModuleKind(value: string): value is EducationalModuleKind { return (educationalModuleKinds as readonly string[]).includes(value); }
export function educationalModulePins(kind: EducationalModuleKind): Record<string, PinNumber> { return Object.fromEntries(educationalModuleSpecs[kind].pins.map(item => [item.key, null])); }
export function validEducationalModuleConfig(kind: EducationalModuleKind, value: unknown): value is EducationalModuleSpec['defaults'] {
  if (!value || typeof value !== 'object' || Array.isArray(value)) return false;
  const config = value as Record<string, unknown>, spec = educationalModuleSpecs[kind];
  if (Object.keys(config).some(key => !['profile','values','settings'].includes(key)) || !spec.profiles.some(profile => profile.id === config.profile)) return false;
  if (!config.values || typeof config.values !== 'object' || Array.isArray(config.values) || !config.settings || typeof config.settings !== 'object' || Array.isArray(config.settings)) return false;
  const values = config.values as Record<string, unknown>;
  if (Object.keys(values).length !== spec.values.length || spec.values.some(item => {
    const candidate = values[item.key];
    return item.type === 'number' ? typeof candidate !== 'number' || !Number.isFinite(candidate) || candidate < (item.min ?? -Infinity) || candidate > (item.max ?? Infinity) : typeof candidate !== (item.type === 'text' ? 'string' : 'boolean') || (item.choices && !item.choices.includes(String(candidate)));
  })) return false;
  return Object.keys(config.settings as object).every(key => key in spec.defaults.settings);
}
