import assert from 'node:assert/strict';
import { separatedBlockOffset, trafficColorLabel } from '../lib/editor-ergonomics.ts';
import { simulatedPinState, rawSimulatedPinState } from '../lib/simulated-pin-state.ts';
const box = { left: 0, right: 100, top: 0, bottom: 80 };
assert.equal(separatedBlockOffset(box, []), 0);
assert.equal(separatedBlockOffset(box, [{ ...box, left: 200, right: 300 }]), 0);
assert.equal(separatedBlockOffset(box, [box]), 104);
assert.equal(separatedBlockOffset(box, [box, { ...box, top: 100, bottom: 200 }]), 224);
assert.equal(separatedBlockOffset({ ...box, left: -300, right: -200 }, [box]), 0);
assert.equal(trafficColorLabel('GREEN'), 'verde');
assert.equal(trafficColorLabel('OFF'), 'apagado');
const traffic = { kind: 'trafficLight' };
assert.equal(simulatedPinState(traffic, 'red', { kind: 'trafficLight', color: 'RED' }).label, '1 · encendido');
assert.equal(simulatedPinState(traffic, 'green', { kind: 'trafficLight', color: 'RED' }).intensity, 0);
assert.equal(simulatedPinState(traffic, 'matrixDin', { kind: 'trafficLight', color: 'RED' }), undefined);
assert.equal(simulatedPinState({ kind: 'led' }, 'signal', { kind: 'led', brightness: 25 }).intensity, .25);
assert.equal(simulatedPinState({ kind: 'potentiometer' }, 'signal', { kind: 'potentiometer', value: 4095 }).intensity, 1);
assert.equal(simulatedPinState({ kind: 'lightSensor' }, 'signal', { kind: 'lightSensor', value: 0 }).intensity, 0);
assert.equal(simulatedPinState({ kind: 'display' }, 'sda', { kind: 'display' }), undefined);
assert.equal(rawSimulatedPinState(false).label, '0 · apagado');
console.log('Ergonomía: geometría libre, nombres y estados simulados aprobados.');
